#ifndef __WINDOW_HPP__
#define __WINDOW_HPP__

// GLUT (OpenGL header)
#include <GL/glut.h>
#include <memory>
#include <string>
#include <map>
#include <memory>

using std::shared_ptr;
using std::make_shared;
using std::string;
using std::map;

#include "../picture/graphics/vertex.hpp"
#include "../picture/graphics/color.hpp"

class Window;

/*
	GLUT window abstract class

	Callbacks duplicated because it's possible to pass
	only static methods to GLUT.
*/

class Window : public std::enable_shared_from_this<Window>
{
public:
	// Window constructor: window size (width; height), window title, background color
	Window(const int& width, const int& height, const char* title);
	virtual ~Window();

	// ### Derived classes callbacks ###
	// rendering function
	virtual void display() = 0;

	// ### mouse and keyboard event handlers ###
	// mouse button pressing
	virtual void mousePress(const int& button, const int& state, const Vertex& mousePos) = 0;
	// mouse moving
	virtual void mouseMove(const Vertex& mousePos) = 0;
	// mouse moving with buttons pressed (drag)
	virtual void mousePressMove(const Vertex& mousePos) = 0;
	// keyboard key press
	virtual void keyPress(unsigned char key, const Vertex& mousePos) = 0;
	// keyboard special key press (F1-F12, Arrows, etc.)
	virtual void keyPressSpecial(const int& key, const Vertex& mousePos) = 0;
	// calls when user changes window size
	virtual void reshape(const int& width, const int& height) = 0;

	// set window background color
	void setBgColor(const float& red, const float& green, const float& blue);
	// set minimal window size
	void setMinSize(const int& width, const int& height);
	// close current window
	void close();

private:

	// initialize GLUT
	static bool Init();
	// initialization status
	static bool initialized;
	// global GLUT callbacks
	static void glutDisplay();
	// button {left, right, middle}, state {pressed, released}, (x, y) - mouse position
	static void glutMousePress(int button, int state, int x, int y);
	// (x, y) - mouse position
	static void glutMouseMove(int x, int y);
	// (x, y) - mouse position
	static void glutMousePressMove(int x, int y);
	// key - character generated by keyboard, (x, y) - mouse position
	static void glutKeyPress(unsigned char key, int x, int y);
	// key - one of special keys (defined as GLUT_KEY_{name})
	static void glutKeyPressSpecial(int key, int x, int y);
	// (width, height) - new window size
	static void glutReshape(int width, int height);
	// check if new window size not less then minimal
	bool checkMinSize(const int &width, const int &height);

	// window ID
	int id;

protected: // available for inherited classes

	// list of all existing windows (int is a GLUT window ID)
	static map<int, Window*> windows;
	// static map<int, std::shared_ptr<Window>> windows;

	// window size
	shared_ptr<int> width;
	shared_ptr<int> height;

	// minimal window size
	int minWidth; 
	int minHeight;
};

#endif // __WINDOW_HPP__